### ISSUE TITLE
Wiki outdated

### ISSUE THREAD

**Issue by paskal** [artmg/nixnote2-packaging#19]
Hi!

I found following wiki page in search: https://github.com/artmg/nixnote2-packaging/wiki/Launchpad-Setup-History

[Quote](http://askubuntu.com/a/854862/34435):

> Launchpad [supports importing git code directly](http://blog.launchpad.net/code/git-to-git-imports) since 16-10-2016, see [the doc](https://help.launchpad.net/Packaging/SourceBuilds/Recipes) for setup instructions.
> 
> A note: if [1084403](https://bugs.launchpad.net/ubuntu/+source/bzr-git/+bug/1084403) bug still open when you're reading this, don't forget to clean your bzr import settings from old setup or you couldn't set a recipe for git code even if it's there.

**Comment by artmg** [comment]
Thanks for this timely info, @paskal - I've just discovered an [import error due to gpgsig commits](https://github.com/artmg/nixnote2-packaging/issues/20) which is blocking the daily PPA builds, and will now be forced to convert the launchpad import to Git. 

I'm so happy the Launchpad team implemented the solution just before we experienced the problem. I'll make sure the wiki page is updated with the resulting steps and info. Cheers

**Comment by artmg** [comment]
I am having the problems you mentioned, @paskal with bzr taking over my recipe, and I can't seem to get it to work - where do I clean my bzr import settings?

**Comment by paskal** [comment]
@artmg, it helped me just to clear everything from bazaar branch settings. It didn't go away, but after recreation of git recipe it was not replaced by bzr.

**Comment by artmg** [comment]
Unfortunately I couldn't find out where to remove this alias, but in the [Recipe Branch syntax](https://help.launchpad.net/Packaging/SourceBuilds/Recipes#Specifying_the_branches) I found the option to _disambiguate_ using the full git URLs for the repos, e.g.
```
https://git.launchpad.net/nixnote2
https://git.launchpad.net/~nixnote/nixnote2/+git/packaging
```
and this seems to work. Now updated in [our Launchpad Recipes wiki page](https://github.com/artmg/nixnote2-packaging/wiki/Launchpad-Recipes)

**Comment by paskal** [comment]
Thank you! Resolving, then.
