### ISSUE TITLE
Menu icon not showed

### ISSUE THREAD

**Issue by mhalano** [artmg/nixnote2-packaging#28]
My NixNote2 from daily builds doesn't show the icon on Unity launcher. I checked and seems there's no icon on package to be showed.

**Comment by artmg** [comment]
This was being caused by upstream improvements in icon location that rely on an install section called `pixmap.extra`. During the launchpad build it appears this icon files is not being picked up (perhaps because the pixmap.extra is being called AFTER the image files have already been copied?) I have added a manual copy in the `rules` for `override_dh_auto_install`.

I will initiate the build now to validate this works.

**Comment by artmg** [comment]
reported upstream as #348 https://github.com/baumgarr/nixnote2/issues/348

**Comment by artmg** [comment]
Validated as working in `2.0-release-0+959+62+201708082214~ubuntu17.10.1` 
(Help / About / `nixnote2-daily+20170809`)
