### ISSUE TITLE
Add Bionic Beaver to the Daily PPA

### ISSUE THREAD

**Issue by fitig** [artmg/nixnote2-packaging#30]
apt throws the following error in 18.04:

 http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu bionic Release   
  404  Not Found [IP: 91.189.95.83 80]
The repository 'http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu bionic Release' does not have a Release file.

**Comment by artmg** [comment]
Have added Bionic and Cosmic to build series for the recipe. Let me know if that resolves the issues. Thanks

**Comment by fitig** [comment]
I get the same error.  Does this update immediately on the Launchpad based PPA?  Any idea how long I need to wait?

**Comment by fitig** [comment]
Just tried again and got the same error.

**Comment by artmg** [comment]
My apologies, but no code has been committed recently to the nixnote2 upstream, so I had to request a build manually (should be ready in less than half an hour). 

You should be aware that the upstream project has had no commits since October 2017 - if you get any issues with the software I'm not sure how quickly they might be fixed. 

Anyhow, let me know if the package for your version becomes available now. Thanks

**Comment by fitig** [comment]
That works now.  Thanks for doing that!

Yeah I would switch to something else instead of Nixnote for my Evernote usage on Ubuntu but haven't found anything that meets my needs.  Most seem to be Electron or other wrappers around the website itself.  Do you have any favorites / suggestions?

**Comment by robert7** [comment]
@github-t you could try my [fork of NixNote](https://github.com/robert7/nixnote2)..
Other option could be [Quentier](https://github.com/d1vanov/quentier)..
